version: '3.8'

services:
  self-service-portal:
    build: .
    container_name: self-service-portal
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-change-this}
    volumes:
      - ./portal-config.json:/app/portal-config.json:ro
      - ./logs:/app/logs
    networks:
      - portal-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.portal.tls=true"
      - "traefik.http.services.portal.loadbalancer.server.port=8080"

networks:
  portal-network:
    driver: bridge 